version: '3.8'

services:
  minecraft-server:
    container_name: minecraft-server
    build:
      context: .
    volumes:
      - ./minecraft-server:/home/minecraft-server/server
      - ./entrypoint.sh:/home/minecraft-server/entrypoint.sh
    ports:
      - 25575:25575
      - 80:80
      - 8080:8080