version: '3.8'

services:
  forge-server:
    container_name: forge-server
    build:
      context: .
    volumes:
      - ./minecraft-server:/home/minecraft-server/server
      - ./entrypoint.sh:/home/minecraft-server/entrypoint.sh